### ISSUE TITLE
SysteMHC: toward a community-driven global mapping of the human immunopeptidome

### ISSUE THREAD

**Issue by eticaron** [SysteMHC/systeMHC#4]
Big picture of the SysteMHC project. 
[HIPP.pdf](https://github.com/SysteMHC/systeMHC/files/50666/HIPP.pdf)

**Comment by wolski** [comment]
I will put the picture in our wiki.
https://github.com/SysteMHC/systeMHC/wiki

**Comment by wolski** [comment]
Added pdf to repository and picture to wiki.
